version: '3.1'
services:
  # other services

  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1234abc'
      MYSQL_DATABASE: 'mydb'
    volumes:
      - /var/lib/mysql
      - ./src/migrations/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "3307:3306"

  app:
    container_name: app
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - mysql
    environment:
      DB_HOST: 'mysql'
      DB_USER: 'root'
      DB_PORT: '3306'
      DB_NAME: 'mydb'
      DB_PWD: '1234abc'
